/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated.files'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated.roles.index'
import { Route as AuthenticatedRolesCreateRouteImport } from './routes/_authenticated.roles.create'
import { Route as AuthenticatedRolesEditRouteImport } from './routes/_authenticated.roles.edit'
import { Route as AuthenticatedSchemasIndexRouteImport } from './routes/_authenticated.schemas.index'
import { Route as AuthenticatedSchemasEditRouteImport } from './routes/_authenticated.schemas.edit'
import { Route as AuthenticatedSchemasNewRouteImport } from './routes/_authenticated.schemas.new'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated.users.index'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated.users.create'
import { Route as AuthenticatedUsersEditRouteImport } from './routes/_authenticated.users.edit'
import { Route as AuthenticatedContentSchemaNameIndexRouteImport } from './routes/_authenticated.content.$schemaName.index'
import { Route as AuthenticatedContentSchemaNameCreateRouteImport } from './routes/_authenticated.content.$schemaName.create'
import { Route as AuthenticatedContentSchemaNameEditRouteImport } from './routes/_authenticated.content.$schemaName.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesCreateRoute =
  AuthenticatedRolesCreateRouteImport.update({
    id: '/roles/create',
    path: '/roles/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesEditRoute = AuthenticatedRolesEditRouteImport.update({
  id: '/roles/edit',
  path: '/roles/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchemasIndexRoute =
  AuthenticatedSchemasIndexRouteImport.update({
    id: '/schemas/',
    path: '/schemas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchemasEditRoute =
  AuthenticatedSchemasEditRouteImport.update({
    id: '/schemas/edit',
    path: '/schemas/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchemasNewRoute = AuthenticatedSchemasNewRouteImport.update({
  id: '/schemas/new',
  path: '/schemas/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersEditRoute = AuthenticatedUsersEditRouteImport.update({
  id: '/users/edit',
  path: '/users/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentSchemaNameIndexRoute =
  AuthenticatedContentSchemaNameIndexRouteImport.update({
    id: '/content/$schemaName/',
    path: '/content/$schemaName/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentSchemaNameCreateRoute =
  AuthenticatedContentSchemaNameCreateRouteImport.update({
    id: '/content/$schemaName/create',
    path: '/content/$schemaName/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentSchemaNameEditRoute =
  AuthenticatedContentSchemaNameEditRouteImport.update({
    id: '/content/$schemaName/edit',
    path: '/content/$schemaName/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/files': typeof AuthenticatedFilesRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/roles/edit': typeof AuthenticatedRolesEditRoute
  '/schemas/edit': typeof AuthenticatedSchemasEditRoute
  '/schemas/new': typeof AuthenticatedSchemasNewRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/users/edit': typeof AuthenticatedUsersEditRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/schemas/': typeof AuthenticatedSchemasIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/content/$schemaName/create': typeof AuthenticatedContentSchemaNameCreateRoute
  '/content/$schemaName/edit': typeof AuthenticatedContentSchemaNameEditRoute
  '/content/$schemaName/': typeof AuthenticatedContentSchemaNameIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/files': typeof AuthenticatedFilesRoute
  '/': typeof AuthenticatedIndexRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/roles/edit': typeof AuthenticatedRolesEditRoute
  '/schemas/edit': typeof AuthenticatedSchemasEditRoute
  '/schemas/new': typeof AuthenticatedSchemasNewRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/users/edit': typeof AuthenticatedUsersEditRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/schemas': typeof AuthenticatedSchemasIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/content/$schemaName/create': typeof AuthenticatedContentSchemaNameCreateRoute
  '/content/$schemaName/edit': typeof AuthenticatedContentSchemaNameEditRoute
  '/content/$schemaName': typeof AuthenticatedContentSchemaNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/roles/create': typeof AuthenticatedRolesCreateRoute
  '/_authenticated/roles/edit': typeof AuthenticatedRolesEditRoute
  '/_authenticated/schemas/edit': typeof AuthenticatedSchemasEditRoute
  '/_authenticated/schemas/new': typeof AuthenticatedSchemasNewRoute
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/users/edit': typeof AuthenticatedUsersEditRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/schemas/': typeof AuthenticatedSchemasIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/content/$schemaName/create': typeof AuthenticatedContentSchemaNameCreateRoute
  '/_authenticated/content/$schemaName/edit': typeof AuthenticatedContentSchemaNameEditRoute
  '/_authenticated/content/$schemaName/': typeof AuthenticatedContentSchemaNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/files'
    | '/roles/create'
    | '/roles/edit'
    | '/schemas/edit'
    | '/schemas/new'
    | '/users/create'
    | '/users/edit'
    | '/roles/'
    | '/schemas/'
    | '/users/'
    | '/content/$schemaName/create'
    | '/content/$schemaName/edit'
    | '/content/$schemaName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/files'
    | '/'
    | '/roles/create'
    | '/roles/edit'
    | '/schemas/edit'
    | '/schemas/new'
    | '/users/create'
    | '/users/edit'
    | '/roles'
    | '/schemas'
    | '/users'
    | '/content/$schemaName/create'
    | '/content/$schemaName/edit'
    | '/content/$schemaName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/files'
    | '/_authenticated/'
    | '/_authenticated/roles/create'
    | '/_authenticated/roles/edit'
    | '/_authenticated/schemas/edit'
    | '/_authenticated/schemas/new'
    | '/_authenticated/users/create'
    | '/_authenticated/users/edit'
    | '/_authenticated/roles/'
    | '/_authenticated/schemas/'
    | '/_authenticated/users/'
    | '/_authenticated/content/$schemaName/create'
    | '/_authenticated/content/$schemaName/edit'
    | '/_authenticated/content/$schemaName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/create': {
      id: '/_authenticated/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthenticatedRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/edit': {
      id: '/_authenticated/roles/edit'
      path: '/roles/edit'
      fullPath: '/roles/edit'
      preLoaderRoute: typeof AuthenticatedRolesEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schemas/': {
      id: '/_authenticated/schemas/'
      path: '/schemas'
      fullPath: '/schemas/'
      preLoaderRoute: typeof AuthenticatedSchemasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schemas/edit': {
      id: '/_authenticated/schemas/edit'
      path: '/schemas/edit'
      fullPath: '/schemas/edit'
      preLoaderRoute: typeof AuthenticatedSchemasEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schemas/new': {
      id: '/_authenticated/schemas/new'
      path: '/schemas/new'
      fullPath: '/schemas/new'
      preLoaderRoute: typeof AuthenticatedSchemasNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/edit': {
      id: '/_authenticated/users/edit'
      path: '/users/edit'
      fullPath: '/users/edit'
      preLoaderRoute: typeof AuthenticatedUsersEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/$schemaName/': {
      id: '/_authenticated/content/$schemaName/'
      path: '/content/$schemaName'
      fullPath: '/content/$schemaName/'
      preLoaderRoute: typeof AuthenticatedContentSchemaNameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/$schemaName/create': {
      id: '/_authenticated/content/$schemaName/create'
      path: '/content/$schemaName/create'
      fullPath: '/content/$schemaName/create'
      preLoaderRoute: typeof AuthenticatedContentSchemaNameCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/$schemaName/edit': {
      id: '/_authenticated/content/$schemaName/edit'
      path: '/content/$schemaName/edit'
      fullPath: '/content/$schemaName/edit'
      preLoaderRoute: typeof AuthenticatedContentSchemaNameEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRolesCreateRoute: typeof AuthenticatedRolesCreateRoute
  AuthenticatedRolesEditRoute: typeof AuthenticatedRolesEditRoute
  AuthenticatedSchemasEditRoute: typeof AuthenticatedSchemasEditRoute
  AuthenticatedSchemasNewRoute: typeof AuthenticatedSchemasNewRoute
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedUsersEditRoute: typeof AuthenticatedUsersEditRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSchemasIndexRoute: typeof AuthenticatedSchemasIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedContentSchemaNameCreateRoute: typeof AuthenticatedContentSchemaNameCreateRoute
  AuthenticatedContentSchemaNameEditRoute: typeof AuthenticatedContentSchemaNameEditRoute
  AuthenticatedContentSchemaNameIndexRoute: typeof AuthenticatedContentSchemaNameIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRolesCreateRoute: AuthenticatedRolesCreateRoute,
  AuthenticatedRolesEditRoute: AuthenticatedRolesEditRoute,
  AuthenticatedSchemasEditRoute: AuthenticatedSchemasEditRoute,
  AuthenticatedSchemasNewRoute: AuthenticatedSchemasNewRoute,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedUsersEditRoute: AuthenticatedUsersEditRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSchemasIndexRoute: AuthenticatedSchemasIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedContentSchemaNameCreateRoute:
    AuthenticatedContentSchemaNameCreateRoute,
  AuthenticatedContentSchemaNameEditRoute:
    AuthenticatedContentSchemaNameEditRoute,
  AuthenticatedContentSchemaNameIndexRoute:
    AuthenticatedContentSchemaNameIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
